services:
  api:
    build:
      context: .
      target: api
    ports:
      - '3000:3000'
    restart: unless-stopped

  web:
    build:
      context: .
      target: web
    ports:
      - '8080:80'
    depends_on:
      - api
    restart: unless-stopped
